---
- hosts: all
  become: true
  pre_tasks:

    - name: add default route for uplink on PXE machine
      ansible.builtin.command: ip route add default via 192.168.255.1 dev eth1
      when: settings['harvester']['airgapped']

    - name: install kitty terminfo
      apt:
        name: kitty-terminfo

  roles:
    - role: dhcp
    - role: tftp
    - role: https
      when: settings['pxe_server']['https']
    - role: http
    - role: ipxe
    - role: harvester
    - role: ntpd
      when: settings['harvester']['airgapped']
    - role: proxy
    - role: s3
      when: settings['s3']['enabled'] | bool
