---
##########################################################################
# NOTE: this is a YAML file so please pay close attention to the leading #
# spaces as they are significant.                                        #
##########################################################################

#
# iso_url
# kernel_url
# initrd_url
#
# Harvester media to install. The URL scheme can be either 'http', 'https', or
# 'file'. If the URL scheme is 'file', the given media will be copied from the
# local file system instead of downloading from a remote location.

iso_url: >-
  file:///home/moritz/harvester/artifacts/harvester-amd64.iso
kernel_url: >-
  file:///home/moritz/harvester/artifacts/harvester-vmlinuz-amd64
ramdisk_url: >-
  file:///home/moritz/harvester/artifacts/harvester-initrd-amd64
rootfs_url: >-
  file:///home/moritz/harvester/artifacts/harvester-rootfs-amd64.squashfs

# Define one or more networks. The first network is going to be the management
# network. It's also going to be used for iPXE, hence it needs parameters `boot`
# and `https`
# Each network here corresponds to a libvirt network
# If dhcp_range is defined, there is going to be a DHCP server at x.x.x.254
networks:
  - name: mgmt
    subnet: 192.168.0.0
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.0.50
      end: 192.168.0.130
    https: false
    boot: true

  - name: storage
    subnet: 192.168.1.0
    netmask: 255.255.255.0

  - name: migrations
    subnet: 192.168.2.0
    netmask: 255.255.255.0

  - name: workloads
    subnet: 192.168.3.0
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.3.50
      end: 192.168.3.250

pxe_server:
  cpu: 2       # Number of vCPUs
  memory_G: 4  # Memory size in GiB
  #  Change this to a custom DNS server if you need one for your DHCP scope
  dns_server: 1.1.1.1

harvester:
  # Run as an airgapped environment that only has internet connectivity through
  # an HTTP proxy. The HTTP proxy runs on DHCP server using port 3128
  airgapped: false
  sftp: true
  token: token

  vip:
    ip: 192.168.0.131
    mode: dhcp
    mac: 02:00:00:03:3D:61

  # Define one or more nodes.
  # Each node can have one or more disks (storage devices) and network
  # interfaces.
  # To add a storage device, specify the device name and size, optionally the
  # bus (virtio by default) and wwn
  # To add a network interface, just name the network which that node needs to
  # be connected to.
  # Mac addresses are going to be generated: 02:00:0X:Yd:62:e2
  # where X is the number of the network starting at 0 and Y is the number of
  # the node starting at 0
  cluster:
    - name: node-1
      cpu: 8
      memory_G: 16
      disks:
        - name: nvme0n1
          size: 300G
          bus: nvme
        - name: sda
          size: 1000G
          bus: scsi
        - name: sdb
          size: 1000G
          bus: scsi
      root_disk: nvme0n1
      data_disk: sda
      networks:
        - mgmt
        - storage
        - workloads
        - migrations
      # role: default, management, witness or worker
      role: default

    - name: node-2
      cpu: 8
      memory_G: 16
      disks:
        - name: nvme0n1
          size: 300G
          bus: nvme
        - name: vda
          size: 1000G
          bus: virtio
        - name: vdb
          size: 1000G
          bus: virtio
      root_disk: nvme0n1
      data_disk: vda
      networks:
        - mgmt
        - storage
        - workloads
        - migrations
      # role: default, management, witness or worker
      role: default

    - name: node-w
      cpu: 4
      memory_G: 8
      disks:
        - name: vda
          size: 300G
          bus: virtio
      root_disk: vda
      data_disk: vda
      networks:
        - mgmt
      # role: default, management, witness or worker
      role: witness

  # These settings are applied to each Harvester node
  global:
    password: p@ssword
    # This is a list of DNS servers that will be included in your Harvester OS
    # config
    dns_servers:
      - 192.168.0.254
      - 8.8.8.8
    ntp_servers:
      - 0.suse.pool.ntp.org
      - 1.suse.pool.ntp.org
    ssh_authorized_keys:
      # Vagrant default unsecured SSH public key
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBJTm386wM5VO8ct2dlg76vdayHt7W+58a3c+Nkue7mrhU+eYguPqgvZpHRCPdPX+SLXTqHRCyvwphPLPD8Q+2McJqFkwLavflIHYcDnjAuasnZiI80YDUmgjajfa7m9lSyoKQ7S+knPN6wgFxjyk8ywCIv5cdxu9X3G14LvADO5yl36vIS66rwXXEc6k3GEw9t1yKYk0JIdW2ormupVrQsHin3NLX34NZU3tR6sfPnXotgP+vZr3KKBUuIe4YU+xk6qzSaDROlbePheY/oNfLJC+jzjE39aKyTxgys/qlS31aL+1sYtaq5gc5/yY6oYPu4H5rLNASxOodU645vnCmA5SOYAxzI5KJSTV+w+puzG3uQ1sdZ57BTnluGj59NHl6A1IKTNbfbNfr3I3WIGRQQ0n3zWzb1pPtRed1A8vGSLYEqEyUtkLHjE2rWWNnXv1lAF3u+SPsMNVbWWw7FV+Ctyrn++//YVUhQFZF1VqLYab2hU13Sq5VtGcMbn3mfgTR1LByXRyb0GE8vlEPf82y+8BAhwceSAdd9oiV9Ek/rM79r86rluG5YY17WOfdao0clEELfJC3yUToGIJ7lidcEmxVO/OF8ZJj1M1OXSBD18imNlpt/eLX3PeJ1o2R0m4iD4CYzzTnzxJtwhubOfyEPl55F1XK9fuNP9CkPikztQ== cardno:000610664588"

# rancher_config
#
# Rancher setup on an independent node.
#
# Support Matrix: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions
# K3s Release: https://docs.k3s.io/release-notes/v1.28.X
#
rancher_config:
  enabled: false
  version: v2.8.5
  repo: https://releases.rancher.com/server-charts/latest

  kubernetes:
    version: v1.28.11+k3s1
    config: /etc/rancher/k3s/k3s.yaml

  # IP should be out of harvester_network_config.dhcp_server.range and does not
  # conflict with other static IPs (e.g. Harvester).
  ip: 192.168.0.141
  hostname: rancher.192.168.0.141.sslip.io
  password: password1234

  cpu: 2
  memory: 4096
