---
# Harvester media to install. The URL scheme can be either 'http', 'https', or
# 'file'. If the URL scheme is 'file', the given media will be copied from the
# local file system instead of downloading from a remote location.
iso_url: >-
  file:///home/moritz/harvester/artifacts/harvester-amd64.iso
kernel_url: >-
  file:///home/moritz/harvester/artifacts/harvester-vmlinuz-amd64
ramdisk_url: >-
  file:///home/moritz/harvester/artifacts/harvester-initrd-amd64
rootfs_url: >-
  file:///home/moritz/harvester/artifacts/harvester-rootfs-amd64.squashfs

# Global Libvirt options. These are host-system specific, needed to properly set
# up the libvirt domains
libvirt:
  connection: qemu:///system
  storage_pool: default
  # On openSUSE the UEFI loader for Qemu is at /usr/share/qemu/ovmf-x86_64.bin,
  # but other distributions may have it at /usr/share/qemu/OVMF.fd
  uefi_firmware_path: /usr/share/qemu/ovmf-x86_64.bin

# Define one or more networks. The first network is going to be the management
# network. It's also going to be used for iPXE, hence it needs parameters `boot`
# and in case it should not be able to reach outside also `airgapped`
# Each network here corresponds to a libvirt network
# If dhcp_range is defined, there is going to be a DHCP server at x.x.x.254
# Example:
#
# - name: foobar
#   subnet: 192.168.42.0
#   netmask: 255.255.255.0
#   dhcp_range:
#     start: 192.168.42.100
#     end: 192.168.42.120
#   boot: false
#   airgapped: true
#
networks:
  - name: mgmt
    subnet: 192.168.0.0
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.0.50
      end: 192.168.0.130
    boot: true

  - name: storage
    subnet: 192.168.1.0
    netmask: 255.255.255.0
    airgapped: true

  - name: workloads-1
    subnet: 192.168.3.0
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.3.50
      end: 192.168.3.250

  - name: workloads-2
    subnet: 192.168.4.0
    netmask: 255.255.255.0
    dhcp_range:
      start: 192.168.4.50
      end: 192.168.4.250
    airgapped: true

pxe_server:
  cpu: 2       # Number of vCPUs
  memory_G: 4  # Memory size in GiB
  # Change this to a custom DNS server if you need one for your DHCP scope
  # In each network, xxx.yyy.zzz.1 is automatically added as DNS server. This
  # server is provided by dnsmasq on the libvirt host
  #dns_server: 1.1.1.1

  # This configures a self-signed certificate on the HTTP server
  https: false

  artifacts:
    - file:///home/moritz/Downloads/ubuntu-24.04-server-cloudimg-amd64.img

harvester:
  # Run as an airgapped environment that only has internet connectivity through
  # an HTTP proxy. The HTTP proxy runs on DHCP server using port 3128
  airgapped: false
  token: token

  vip:
    ip: 192.168.0.131
    mode: dhcp
    mac: 02:00:00:03:3D:6e

  # These settings are applied to each Harvester node
  global:
    # Enable SFTP service
    #sftp: true

    # Login password for user `rancher` on each node
    password: p@ssword

    # This is a list of DNS servers that will be included in your Harvester OS
    # config
    dns_servers:
      - 192.168.0.1

    # If running in an airgapped environment, these servers will be configured
    # as NTP peers on the PXE server and the PXE server will be NTP server for
    # the Harvester cluster. Otherwise these servers will be NTP servers for the
    # Harvester cluster directly.
    ntp_servers:
      - 0.suse.pool.ntp.org
      - 1.suse.pool.ntp.org
    ssh_authorized_keys: []

  # These settings are applied to each Harvester node
  global:
    # Enable SFTP service
    #sftp: true

    # Login password for user `rancher` on each node
    password: p@ssword

    # This is a list of DNS servers that will be included in your Harvester OS
    # config
    dns_servers:
      - 192.168.0.1

    # If running in an airgapped environment, these servers will be configured
    # as NTP peers on the PXE server and the PXE server will be NTP server for
    # the Harvester cluster. Otherwise these servers will be NTP servers for the
    # Harvester cluster directly.
    ntp_servers:
      - 0.suse.pool.ntp.org
      - 1.suse.pool.ntp.org
    ssh_authorized_keys: []

  # Define one or more nodes.
  # Each node can have one or more disks (storage devices) and network
  # interfaces.
  # To add a storage device, specify the device name and size, optionally the
  # bus (virtio by default) and wwn
  # To add a network interface, just name the network which that node needs to
  # be connected to.
  # Mac addresses are going to be generated: 02:00:0X:Yd:62:e2
  # where X is the number of the network starting at 0 and Y is the number of
  # the node starting at 0
  #
  # Example:
  #
  # - name: harvester
  #   cpu: 12
  #   memory_G: 32
  #   disks:
  #     - name: nvme0n1
  #       size: 300G
  #       bus: nvme
  #     - name: vda
  #       size: 1000G
  #       bus: virtio
  #     - name: sda
  #       size: 1000G
  #       bus: scsi
  #   root_disk: nvme0n1
  #   data_disk: sda
  #   networks:
  #     - mgmt
  #     - foobar
  #   role: default
  #   uefi: true
  cluster:

    - name: harv0
      cpu: 8
      memory_G: 16
      disks:
        - name: vda
          size: 300G
          bus: virtio
        - name: vdb
          size: 1000G
          bus: virtio
      root_disk: vda
      data_disk: vdb
      networks:
        - mgmt
      role: default
      uefi: true

    - name: harv1
      cpu: 8
      memory_G: 16
      disks:
        - name: vda
          size: 300G
          bus: virtio
        - name: vdb
          size: 1000G
          bus: virtio
      root_disk: vda
      data_disk: vdb
      networks:
        - mgmt
      role: default
      uefi: true

    - name: wit
      cpu: 4
      memory_G: 8
      disks:
        - name: vda
          size: 500G
          bus: virtio
      root_disk: vda
      data_disk: vda
      networks:
        - mgmt
      role: default
      uefi: true

    #  - name: harv0
    #    cpu: 16
    #    memory_G: 32
    #    disks:
    #      - name: vda
    #        size: 300G
    #        bus: virtio
    #      - name: vdb
    #        size: 1000G
    #        bus: virtio
    #    root_disk: vda
    #    data_disk: vdb
    #    networks:
    #      - mgmt
    #    role: default
    #    uefi: true

#    - name: harv0
#      cpu: 16
#      memory_G: 36
#      disks:
#        - name: vda
#          size: 1000G
#          bus: virtio
#      root_disk: vda
#      data_disk: vda
#      networks:
#        - mgmt
#      role: default
#      uefi: true

# Some examples below:
#
#    - name: harv0
#      cpu: 8
#      memory_G: 16
#      disks:
#        - name: vda
#          size: 300G
#          bus: virtio
#        - name: sda
#          size: 1000G
#          bus: scsi
#        - name: nvme0n1
#          size: 1000G
#          bus: nvme
#      root_disk: vda
#      data_disk: vda
#      networks:
#        - mgmt
#        - storage
#        - migrations
#        - workloads-1
#        - workloads-2
#      # role: default, management, witness or worker
#      role: default
#      uefi: true
#
#    - name: harv1
#      cpu: 8
#      memory_G: 16
#      disks:
#        - name: vda
#          size: 300G
#          bus: virtio
#        - name: sda
#          size: 1000G
#          bus: scsi
#        - name: nvme0n1
#          size: 1000G
#          bus: nvme
#      root_disk: vda
#      data_disk: vda
#      networks:
#        - mgmt
#        - storage
#        - migrations
#        - workloads-1
#        - workloads-2
#      # role: default, management, witness or worker
#      role: default
#      uefi: true
#
#    - name: wit
#      cpu: 4
#      memory_G: 8
#      disks:
#        - name: vda
#          size: 300G
#          bus: virtio
#      root_disk: vda
#      data_disk: vda
#      networks:
#        - mgmt
#      # role: default, management, witness or worker
#      role: witness
#      uefi: true


# rancher_config
#
# Rancher setup on an independent node.
#
# Support Matrix: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions
# K3s Release: https://docs.k3s.io/release-notes/v1.28.X
#
rancher_config:
  enabled: false
  version: v2.8.5
  repo: https://releases.rancher.com/server-charts/latest

  kubernetes:
    version: v1.28.11+k3s1
    config: /etc/rancher/k3s/k3s.yaml

  # IP should be out of harvester_network_config.dhcp_server.range and does not
  # conflict with other static IPs (e.g. Harvester).
  ip: 192.168.0.141
  hostname: rancher.192.168.0.141.sslip.io
  password: password1234

  cpu: 2
  memory: 4096
