# vi: set ft=ruby ts=2 :

require 'yaml'
require 'nokogiri'
require 'etc'

VAGRANTFILE_API_VERSION = "2"

# check for required plugins
_required_plugins_list = %w{vagrant-libvirt}
exit(1) unless _required_plugins_list.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    STDERR.puts "Required plugin '#{plugin}' is missing; please install using:"
    STDERR.puts "  % vagrant plugin install #{plugin}"
    false
  )
end

# ensure libvirt is the default provider in case the vagrant box config
# doesn't specify it
ENV['VAGRANT_DEFAULT_PROVIDER'] = "libvirt"

@root_dir = File.dirname(File.expand_path(__FILE__))
@settings = YAML.load_file(File.join(@root_dir, "settings.yml"))

@libvirt_connection = 'qemu:///system'
if @settings.key?('libvirt') and @settings['libvirt'].key?('connection')
  @libvirt_connection = @settings['libvirt']['connection']
end

@libvirt_pool = 'default'
if @settings.key?('libvirt') and @settings['libvirt'].key?('storage_pool')
  @libvirt_pool = @settings['libvirt']['storage_pool']
end

@libvirt_uefi_firmware = '/usr/share/qemu/ovmf-x86_64.bin'
if @settings.key?('libvirt') and @settings['libvirt'].key?('uefi_firmware_path')
  @libvirt_uefi_firmware = @settings['libvirt']['uefi_firmware_path']
end

@virsh = "virsh -c #{@libvirt_connection}"
@pool_path = Nokogiri::XML(%x(#{@virsh} pool-dumpxml --pool #{@libvirt_pool})).at_xpath('/pool/target/path').content

def create_nvme(trigger, name, size, type)
  trigger.name= "Creating volume #{name}"

  owner = begin
            Etc.getpwnam('qemu')
          rescue
            Etc.getpwnam('root')
          end

  trigger.run = {inline: "sh -c \"\
    #{@virsh} vol-info --pool #{@libvirt_pool} #{name} >/dev/null 2>&1 || \
    #{@virsh} vol-create-as --pool #{@libvirt_pool} #{name} \
      --capacity #{size} \
      --format #{type} \
      --print-xml | \
    sed '/<target>/a <permissions><owner>#{owner.uid}</owner><group>#{owner.gid}</group></permissions>' | \
    #{@virsh} vol-create --pool #{@libvirt_pool} /dev/stdin 2>&1\""}
end

def delete_nvme(trigger, name)
  trigger.name = "Destroying volume #{name}"
  trigger.run = {inline: "sh -c \"\
    #{@virsh} vol-info --pool #{@libvirt_pool} #{name} >/dev/null 2>&1 && \
    #{@virsh} vol-delete --pool #{@libvirt_pool} #{name} >/dev/null 2>&1 || :\""}
end

def generate_wwn(node_idx, disk_idx)
  # This will generate a WWN of the form
  # 0x5100000000000001
  # which will be unique within the virtual cluster
  return (5836665117072162817 + (1000 * node_idx) + disk_idx).to_s(16)
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # continerd is taking more than 60 seconds to shutdown in SUSE platforms
  # so increase the timeout to 120 seconds
  config.vm.graceful_halt_timeout = 120

  # If the environment is airgapped, the management network will also not be
  # nat'ed to the outside
  if @settings['harvester']['airgapped']
    config.vm.provider 'libvirt' do |lv, cfg|
      lv.management_network_mode = 'none'
    end
  end

  ## PXE Server
  ##
  ## The PXE server provides a number of crucial network services, like NTP,
  ## DNS and DHCP
  config.vm.define :pxe_server do |pxe_server|
    pxe_server.vm.box = 'generic/debian11'
    pxe_server.vm.hostname = 'pxe-server'

    # If the environment is airgapped, the PXE server gets an additional nat'ed
    # network to connect to the outside.
    if @settings['harvester']['airgapped']
      pxe_server.vm.network 'private_network',
        ip: '192.168.255.254',
        libvirt__network_name: 'uplink',
        libvirt__dhcp_enabled: false
    end

    # The PXE server is connected to all internal networks, so it can provide
    # DHCP, DNS, NTP etc. on those networks.
    nets = @settings['networks']
    nets.each_with_index do |net, net_idx|
      airgapped = false
      if @settings['harvester']['airgapped'] or (net.key?('airgapped') and net['airgapped'])
        airgapped = true
      end

      pxe_server.vm.network 'private_network',
        ip: "#{net['subnet'][0, net['subnet'].length - 1]}254",
        libvirt__network_name: net['name'],
        libvirt__dhcp_enabled: false,
        libvirt__forward_mode: airgapped ? 'none' : 'nat'
    end

    pxe_server.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = @settings['pxe_server'].key?('memory_G') ? @settings['pxe_server']['memory_G'] * 1024 : 4096
      libvirt.cpus = @settings['pxe_server'].key?('cpu') ? @settings['pxe_server']['cpu'] : 2

      if @settings['s3']['enabled']
        libvirt.storage :file,
          size: @settings['s3']['capacity'],
          type: 'qcow2',
          bus: 'virtio',
          device: 'vdb'
      end
    end

    pxe_server.vm.provision :ansible do |ansible|
      ansible.playbook = 'ansible/setup_pxe_server.yml'
      ansible.extra_vars = {
        settings: @settings
      }
    end
  end

  ## Harvester
  ##
  ## Each Harvester node gets its own hardware configuration. It is then booted
  ## from the network to provision the software on it.
  nodes = @settings['harvester']['cluster']
  nodes.each_with_index do |node, node_idx|
    vm_name = node.key?('name') ? node['name'] : "node-#{node_idx}"
    config.vm.define vm_name, autostart: false do |harvester_node|
      harvester_node.vm.hostname = vm_name

      boot_network = {'network' => @settings['networks'][0]['name']}
      # Connect the node only to the networks specified in the settings
      nets = @settings['networks']
      nets.each_with_index do |net, net_idx|
        if net.key?('boot') and net['boot'] == true
          boot_network = {'network' => net['name']}
        end

        if node['networks'].include? net['name']
          harvester_node.vm.network 'private_network',
            libvirt__network_name: net['name'],
            mac: "02:00:00:03:3E:#{net_idx}#{node_idx}"
        end
      end

      harvester_node.vm.provider :libvirt do |libvirt|
        # libvirt.nested = true
        if node.key?('arch') and node['arch'] == 'arm64'
          libvirt.driver = 'qemu'
          libvirt.features = ['apic', 'pae', "gic version='3'"]
          libvirt.inputs = []

          # libvirt.graphics_port = 5900 + node_idx
          # libvirt.graphics_passwd = 'vnc'
          libvirt.video_type = 'vga'
          libvirt.qemuargs :value => '-device'
          libvirt.qemuargs :value => 'virtio-gpu-pci,addr=12'

          libvirt.cpu_mode = 'custom'
          libvirt.cpu_model = 'cortex-a72'
          libvirt.machine_arch = 'aarch64'
          libvirt.machine_type = 'virt'
        else
          libvirt.cpu_mode = 'host-passthrough'
          libvirt.machine_arch = 'x86_64'
        end

        libvirt.cpus = node.key?('cpu') ? node['cpu'] : 4
        libvirt.memory = node.key?('memory_G') ? (node['memory_G'] * 1024) : 8192

        libvirt.boot 'hd'
        libvirt.boot boot_network
        libvirt.nic_model_type = 'virtio'

        # Don't attach vagrant management network, figure out SSH access through
        # Harvester's cluster networks.
        libvirt.mgmt_attach = false
        libvirt.qemu_use_agent = true
        harvester_node.ssh.host = "#{@settings['networks'][0]['subnet'][0, @settings['networks'][0]['subnet'].length - 1]}1#{node_idx}"
        harvester_node.ssh.username = "rancher"

        # Setup UEFI booting, unless explicitly disabled.
        if not node.key?('uefi') or node['uefi'] == true
          libvirt.loader = @libvirt_uefi_firmware

          if node.key?('arch') and node['arch'] == 'arm64'
            libvirt.loader = '/usr/share/qemu/aavmf-aarch64-code.bin'
          end
        end

        # Disks
        disks = node['disks']
        disks.each_with_index do |disk, disk_idx|
          if disk['bus'] == 'scsi'
            # If it's a SCSI disk, we need to generate a wwn if non is given.
            libvirt.storage :file,
              device: disk['name'],
              size: disk['size'],
              type: disk.key?('type') ? disk['type'] : 'qcow2',
              bus: disk['bus'],
              cache: disk.key?('cache') ? disk['cache'] : 'default',
              wwn: disk.key?('wwn') ? disk['wwn'] : generate_wwn(node_idx, disk_idx)
          elsif disk['bus'] == 'nvme'
            # NVMe is not directly supported by Vagrant. Hence we need to use raw
            # qemu command line arguments to attach an NVMe drive. This also
            # means we need to manage the backing image file ourselves
            nvme_type = disk.key?('type') ? disk['type'] : 'qcow2'
            nvme_name = "#{File.basename(@root_dir)}_#{vm_name}-#{disk['name']}.#{nvme_type}"
            nvme_path = File.join(@pool_path, nvme_name)

            bootidx_str = ""
            if node.key?('root_disk')
              if node['root_disk'] == disk['name']
                bootidx_str = ",bootindex=0"
              end
            else
              if disk_idx == 0
                bootidx_str = ",bootindex=0"
              end
            end

            serial_nr = "#{node_idx}#{disk_idx}_1234"
            addr = 6 + nets.length + disk_idx

            libvirt.qemuargs :value => '-drive'
            libvirt.qemuargs :value => "file=#{nvme_path},if=none,id=#{disk['name']}"
            libvirt.qemuargs :value => '-device'
            libvirt.qemuargs :value => "nvme,addr=#{addr},drive=#{disk['name']},serial=#{serial_nr}#{bootidx_str}"

            harvester_node.trigger.before :up do |trigger|
              create_nvme(trigger, nvme_name, disk['size'], nvme_type)
            end

            harvester_node.trigger.before :destroy do |trigger|
              delete_nvme(trigger, nvme_name)
            end
          else
            # By default, just attach the disk as virtio drive.
            libvirt.storage :file,
              device: disk['name'],
              size: disk['size'],
              type: disk.key?('type') ? disk['type'] : 'qcow2',
              bus: disk.key?('bus') ? disk['bus'] : 'virtio',
              cache: disk.key?('cache') ? disk['cache'] : 'default'
          end
        end
      end
    end
  end

  # Rancher
  if @settings['rancher_config']['enabled']
    config.vm.define :rancher do |rancher|
      rancher.vm.box = 'generic/debian10'
      rancher.vm.hostname = 'rancher'
      rancher.vm.network 'private_network',
        ip: @settings['rancher_config']['ip'],
        libvirt__network_name: 'harvester',
        libvirt__dhcp_enabled: false

        rancher.vm.provider :libvirt do |libvirt|
        libvirt.cpu_mode = 'host-passthrough'
        libvirt.cpus = @settings['rancher_config']['cpu']
        libvirt.memory = @settings['rancher_config']['memory']
      end

      rancher.vm.provision :ansible do |ansible|
        ansible.playbook = 'ansible/setup_rancher.yml'
        ansible.extra_vars = {
          settings: @settings
        }
      end
    end
  end

end
